#!/usr/bin/env python3
# pragma: no cover
"""Built-in predicates shipped with Selinon."""

from .alwaysFalse import alwaysFalse
from .alwaysTrue import alwaysTrue
from .argsEmpty import argsEmpty
from .argsFieldBool import argsFieldBool
from .argsFieldContain import argsFieldContain
from .argsFieldDict import argsFieldDict
from .argsFieldEqual import argsFieldEqual
from .argsFieldExist import argsFieldExist
from .argsFieldFloat import argsFieldFloat
from .argsFieldGreater import argsFieldGreater
from .argsFieldGreaterEqual import argsFieldGreaterEqual
from .argsFieldInt import argsFieldInt
from .argsFieldLenEqual import argsFieldLenEqual
from .argsFieldLenGreater import argsFieldLenGreater
from .argsFieldLenGreaterEqual import argsFieldLenGreaterEqual
from .argsFieldLenLess import argsFieldLenLess
from .argsFieldLenLessEqual import argsFieldLenGreaterEqual
from .argsFieldLenNotEqual import argsFieldLenNotEqual
from .argsFieldLess import argsFieldLess
from .argsFieldLessEqual import argsFieldLessEqual
from .argsFieldList import argsFieldList
from .argsFieldNone import argsFieldNone
from .argsFieldNotEqual import argsFieldNotEqual
from .argsFieldStr import argsFieldStr
from .argsFieldUrlNetloc import argsFieldUrlNetloc
from .argsFieldUrlPath import argsFieldUrlPath
from .argsFieldUrlScheme import argsFieldUrlScheme
from .argsIsBool import argsIsBool
from .argsIsDict import argsIsDict
from .argsIsFloat import argsIsFloat
from .argsIsInt import argsIsInt
from .argsIsList import argsIsList
from .argsIsNone import argsIsNone
from .argsIsStr import argsIsStr
from .empty import empty
from .envEqual import envEqual
from .envExist import envExist
from .fieldBool import fieldBool
from .fieldContain import fieldContain
from .fieldDict import fieldDict
from .fieldEqual import fieldEqual
from .fieldExist import fieldExist
from .fieldFloat import fieldFloat
from .fieldGreater import fieldGreater
from .fieldGreaterEqual import fieldGreaterEqual
from .fieldInt import fieldInt
from .fieldLenEqual import fieldLenEqual
from .fieldLenGreater import fieldLenGreater
from .fieldLenGreaterEqual import fieldLenGreaterEqual
from .fieldLenLess import fieldLenLess
from .fieldLenLessEqual import fieldLenGreaterEqual
from .fieldLenNotEqual import fieldLenNotEqual
from .fieldLess import fieldLess
from .fieldLessEqual import fieldLessEqual
from .fieldList import fieldList
from .fieldNone import fieldNone
from .fieldNotEqual import fieldNotEqual
from .fieldStr import fieldStr
from .fieldUrlNetloc import fieldUrlNetloc
from .fieldUrlPath import fieldUrlPath
from .fieldUrlScheme import fieldUrlScheme
from .httpStatus import httpStatus
from .isBool import isBool
from .isDict import isDict
from .isFloat import isFloat
from .isInt import isInt
from .isList import isList
from .isNone import isNone
from .isStr import isStr
