#!/bin/bash

selinonlib-cli plot --nodes-definition dinner.yaml --flow-definitions dinner.yaml --format png --output-dir .

# To get autogenerated output for Dispatcher:
#selinonlib-cli inspect --nodes-definition dinner.yaml --flow-definitions dinner.yaml --dump out.py

