#!/bin/bash

selinonlib-cli -nodes-definition dinner.yaml -flow-definition dinner.yaml -graph graph/ -graph-format png

# To get autogenerated output for Dispatcher:
#selinonlib-cli -nodes-definition dinner.yaml -flow-definition dinner.yaml -dump out.py

