#!/bin/bash

set -x

selinonlib-cli plot --nodes-definition dinner.yaml --flow-definitions dinner.yaml --format png --output-dir . || exit 1
echo 'Generated flows are present in the current directory'

# To get autogenerated output for Dispatcher:
#selinonlib-cli inspect --nodes-definition dinner.yaml --flow-definitions dinner.yaml --dump out.py

